version: "2.2"
services:
  web:
    container_name: fast_web
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - "./www:/usr/share/nginx/html"
      - "./docker/default.conf:/etc/nginx/conf.d/default.conf"
